name: publish image

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      id-token: write # for signing attestations and cache entries with GitHub OIDC
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: |
        docker.io/julieio/agent-devcontainer
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=match,pattern=(v\d+)\.\d+,group=1
        type=semver,pattern={{version}}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
